### ISSUE TITLE
crash , when i click the "ADD PLANT" button.

### ISSUE THREAD

**Issue by pdog18** [android/sunflower#820]
Process: com.google.samples.apps.sunflower, PID: 5144
                                                                                                    java.lang.NoSuchMethodError: No interface method registerOnBackInvokedCallback(ILandroid/window/OnBackInvokedCallback;)V in class Landroid/window/OnBackInvokedDispatcher; or its super classes (declaration of 'android.window.OnBackInvokedDispatcher' appears in /system/framework/framework.jar!classes4.dex)
                                                                                                    	at androidx.activity.OnBackPressedDispatcher$Api33Impl.registerOnBackInvokedCallback(OnBackPressedDispatcher.java:333)
                                                                                                    	at androidx.activity.OnBackPressedDispatcher.updateBackInvokedCallbackState(OnBackPressedDispatcher.java:92)
                                                                                                    	at androidx.activity.OnBackPressedDispatcher.lambda$new$0$androidx-activity-OnBackPressedDispatcher(OnBackPressedDispatcher.java:127)
                                                                                                    	at androidx.activity.OnBackPressedDispatcher$$ExternalSyntheticLambda0.accept(Unknown Source:4)
                                                                                                    	at androidx.activity.OnBackPressedCallback.setEnabled(OnBackPressedCallback.java:79)
                                                                                                    	at androidx.fragment.app.FragmentManager.updateOnBackPressedCallbackEnabled(FragmentManager.java:634)
                                                                                                    	at androidx.fragment.app.FragmentManager.scheduleCommit(FragmentManager.java:1678)
                                                                                                    	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1661)
                                                                                                    	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
                                                                                                    	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
                                                                                                    	at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.kt:196)
                                                                                                    	at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.kt:164)
                                                                                                    	at androidx.navigation.NavController.navigateInternal(NavController.kt:260)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1719)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1545)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1472)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1930)
                                                                                                    	at com.google.samples.apps.sunflower.adapters.PlantAdapter$PlantViewHolder.navigateToPlant(PlantAdapter.kt:63)
                                                                                                    	at com.google.samples.apps.sunflower.adapters.PlantAdapter$PlantViewHolder.access$navigateToPlant(PlantAdapter.kt:45)
                                                                                                    	at com.google.samples.apps.sunflower.adapters.PlantAdapter$PlantViewHolder$bind$1$1$1$1.invoke(PlantAdapter.kt:52)
                                                                                                    	at com.google.samples.apps.sunflower.adapters.PlantAdapter$PlantViewHolder$bind$1$1$1$1.invoke(PlantAdapter.kt:51)
                                                                                                    	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Clickable.kt:167)
                                                                                                    	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:156)
                                                                                                    	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:234)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:566)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:456)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:469)
                                                                                                    	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(BackwardsCompatNode.kt:394)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:314)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
2022-12-29 13:41:39.680  5144-5144  AndroidRuntime          com.google.samples.apps.sunflower    E  	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
                                                                                                    	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
                                                                                                    	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:98)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1329)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1275)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1214)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:499)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1898)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4231)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:457)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:15209)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6599)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6386)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5864)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5921)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5887)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6052)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5895)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6109)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5868)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5921)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5887)
2022-12-29 13:41:39.681  5144-5144  AndroidRuntime          com.google.samples.apps.sunflower    E  	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5895)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5868)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8882)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8833)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8802)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9005)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:161)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7844)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@a991e2c, androidx.compose.runtime.BroadcastFrameClock@c6b70f5, StandaloneCoroutine{Cancelling}@8a7ee8a, AndroidUiDispatcher@2eaccfb]

**Comment by pdog18** [comment]
Emulator with sdk-33 bug
